package request.commands;

public enum UserCommands {
    GET_FURNITURE_LIST,
    GET_FURNITURE_CATEGORY_LIST,
    ADD_CART_ELEMENT,
    CLEAR_CART,
    EXIT,
    CHANGE_PERSONAL_DATA,
    GET_CART_ELEMENT_LIST,
    DELETE_FROM_CART,
    CART_ELEMENT_CHANGE_AMOUNT,
    CREATE_ORDER,
    GET_USER_ORDER_LIST,
    DELETE_ORDER,
    GET_SERVICED_ORDER_LIST
}
